//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnbreakDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDADEMPRESAS
    {
        public ACTIVIDADEMPRESAS()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public int IdActividadEmpresa { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
    }
}
