//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnbreakDALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnbreakDBEntities : DbContext
    {
        public OnbreakDBEntities()
            : base("name=OnbreakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTIVIDADEMPRESAS> ACTIVIDADEMPRESAS { get; set; }
        public DbSet<CLIENTES> CLIENTES { get; set; }
        public DbSet<CONTRATOS> CONTRATOS { get; set; }
        public DbSet<MODALIDADSERVICIOS> MODALIDADSERVICIOS { get; set; }
        public DbSet<TIPOEMPRESAS> TIPOEMPRESAS { get; set; }
        public DbSet<TIPOEVENTOS> TIPOEVENTOS { get; set; }
    }
}
